### PR TITLE
For `forbid_extra_keys` raise custom `ForbiddenExtraKeyError`

### PR DESCRIPTION
**Pull request by raabf**
When `forbid_extra_keys` is actived, I would like to be able to try-except that specific Problem (here `ForbiddenExtraKeyError`) instead of any `Exception`.

The unit tests also gain a little more percition through that change.

### CODE REVIEW

**Comment by Tinche** [comment]
I think this is a good idea but it should wait until after the extended validation branch is merged, which is blocked by other things temporarily.

**Comment by raabf** [comment]
Sure, order the MR as it fits best. :smile:

**Comment by Tinche** [comment]
Hello, I'm preparing a new release and let's get this merged!

So please rebase, and I would ask for a change: add a field to the exception (`extra_keys`) that carries the list of extra keys. This will make it easier to introspect these exceptions programmatically.

**Comment by raabf** [comment]
> add a field to the exception (extra_keys) that carries the list of extra keys. This will make it easier to introspect these exceptions programmatically.

Yea that is nice – I have added this and a reference to class to which the extra keys should be used (i.e. to which class constructor the extra keys were passed). I also extended unit test to check that attributes.

However, there is a small problem, since `ForbiddenExtraKeysError` can conflict with `ClassValidationError`. I assumed that an  `ForbiddenExtraKeysError` means that the Class Validation failed. That means if `ClassValidationError` is used, I add `ForbiddenExtraKeysError` to the `errors` list which is then passed to the `ClassValidationError`. This is more or less anyway implicitly done, because if `ForbiddenExtraKeysError` in a nested class is raised it will be catched anyway by its upper class because you have added ` except Exception as e:` to every attribute. See this commit where I have implemented this behaviour https://github.com/python-attrs/cattrs/pull/225/commits/fd5a9b842da2185b3d04046c1fa38aa533e209da . I hope this is what you have intended.

**Comment by raabf** [comment]
So that it is easy to understand this is an example generated structure function (unknows_fields are added to `errors` list):

```python
def structure_A(o, _, *, __cl=__cl, __c_cve=__c_cve, __c_structure_c=__c_structure_c, __c_type_c=__c_type_c, __c_structure_a=__c_structure_a):
  res = {}
  errors = []
  try:
    res['c'] = __c_structure_c(o['c'], __c_type_c)
  except Exception as e:
    e.__note__ = 'Structuring class test_forbid_extra_keys_nested_override.<locals>.A @ attribute c'
    errors.append(e)
  if 'a' in o:
    try:
      res['a'] = __c_structure_a(o['a'])
    except Exception as e:
      e.__note__ = 'Structuring class test_forbid_extra_keys_nested_override.<locals>.A @ attribute a'
      errors.append(e)
  unknown_fields = set(o.keys()) - __c_a
  if unknown_fields:
    errors.append(__c_feke('', __cl, unknown_fields)) 
  if errors: raise __c_cve('While structuring A', errors, __cl)
  try:
    return __cl(
      **res,
    )
  except Exception as exc: raise __c_cve('While structuring A', [exc], __cl)
```

**Comment by Tinche** [comment]
Yep, that looks great. Thanks a lot!

**Pull request merged**
