### PR TITLE
Fix inconsistent `tuple/typing.Tuple` unstructuring

### LINKED ISSUE #214: GenConverter unstructures tuple to list if in union type.
* cattrs version: 1.10
* Python version: 3.9.7
* Operating System: Windows 10

### Description

GenConverter incorrectly unstructures tuples when in union (or optional). Converter does do it correctly.

Example:
```
from typing import Optional, Tuple
import cattr

orig = (1,'2')

c = cattr.Converter()
print( c.unstructure(orig, Tuple[int,str] ) )
# -> (1, '2')
print( c.unstructure(orig, Optional[Tuple[int,str]] ) )
# -> (1, '2')

c = cattr.GenConverter()
print( c.unstructure(orig, Tuple[int,str] ) )
# -> (1, '2')
print( c.unstructure(orig, Optional[Tuple[int,str]] ) )
# -> [1, '2']    <<< incorrect, no more tuple
```

### LINKED ISSUE #226: Inconsistent unstructuring of `tuple` and `typing.Tuple`
* cattrs version: 22.1.dev0 - 3ee4b40fe1fe64a6c68157f9a9abe43e232f69c7
* Python version: 3.10.1
* Operating System: irrelevant

### Description

Unstructuring tuples work differently if they are annotated as `tuple` and `typing.Tuple`.

Also, unstructuring differs if the tuple is variable-length or precisely known.

### What I Did

Consider these 6 classes:

```python
import typing as t
import attrs
import cattrs

@attrs.define
class T1:
    xs: tuple

@attrs.define
class T2:
    xs: t.Tuple

@attrs.define
class T3:
    xs: tuple[int, str, float]

@attrs.define
class T4:
    xs: t.Tuple[int, str, float]

@attrs.define
class T5:
    xs: tuple[float, ...]

@attrs.define
class T6:
    xs: t.Tuple[float, ...]
```

Now, if you unstructure each of them, you get:

```python
>>> converter.unstructure(T1(xs=(1, "2", 3.4)))
{'xs': [1, '2', 3.4]}
>>> converter.unstructure(T2(xs=(1, "2", 3.4)))
{'xs': (1, '2', 3.4)}


>>> converter.unstructure(T3(xs=(1, "2", 3.4)))
{'xs': (1, '2', 3.4)}
>>> converter.unstructure(T4(xs=(1, "2", 3.4)))
{'xs': (1, '2', 3.4)}


>>> converter.unstructure(T5(xs=(1, "2", 3.4)))
{'xs': [1, '2', 3.4]}
>>> converter.unstructure(T6(xs=(1, "2", 3.4)))
{'xs': [1, '2', 3.4]}

```
### What I expected

I think you mentioned in some other issue, that unstructuring tuples into lists is more natural, since lists are supported by more languages and I agree with that, therefore I expected all the unstructurings to produce a list.

---

As an aside, structuring works correctly for all the cases, so a dictionary `{"xs": [1, '2', 3.4]}` always produces a tuple, and, in the case of `T5/6`, all the values are converted to `float`.

### PR DESCRIPTION
**Pull request by bibajz**
Fixes #226
Fixes #214

Now, all tuples are unstructured to `list` by default.

<strike>Needs a changelog entry and</strike> we are ready to go!

### CODE REVIEW

**Comment by bibajz** [comment]
Hi @Tinche, is this ok? Or would you add something?

**Comment by Tinche** [comment]
Looks ok, will take another look and maybe merge later. 👍

**Comment by bibajz** [comment]
> Looks ok, will take another look and maybe merge later. +1

Got it, thanks!

**Comment by Tinche** [comment]
Merged, thanks!

**Pull request merged**
