### PR TITLE
Remove uses of _cattr_forbid_extra_keys in documentation and test

### PR DESCRIPTION
**Pull request by jevhen-ponomarenko**
#184

### CODE REVIEW

**Comment by Tinche** [comment]
Thanks! A little unclear on how the test was passing with the wrong argument though.

**Comment by Tinche** [comment]
> Thanks! A little unclear on how the test was passing with the wrong argument though.

Ah, it's because the argument defaults to false.

You need to format `tests/metadata/test_genconverter.py` with Black for the lint to pass, btw ;)

**Comment by jevhen-ponomarenko** [comment]
> You need to format tests/metadata/test_genconverter.py with Black for the lint to pass, btw ;)

Sorry still having a hard time with installing all of the Python dependencies on Apple Silicon. 

Since the current test suite didn't catch this bug do you think another unit test should be added?

**Comment by Tinche** [comment]
> > You need to format tests/metadata/test_genconverter.py with Black for the lint to pass, btw ;)
> 
> Sorry still having a hard time with installing all of the Python dependencies on Apple Silicon.
> 
> Since the current test suite didn't catch this bug do you think another unit test should be added?

Nah, the test was valid, it was just trying to set the variable to its default value.

**Pull request closed without merging**
